# Generated by Django 5.2.9 on 2026-07-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("SALES", "Sales"),
                    ("SUPPORT", "Support"),
                ],
                default="SALES",
                max_length=7,
            ),
        ),
    ]
