# Generated by Django 5.2.9 on 2026-07-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Sales", "Sales"),
                    ("Support", "Support"),
                ],
                default="Sales",
                max_length=10,
            ),
        ),
    ]
