# Generated by Django 5.2.9 on 2026-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="remaining_duration",
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_key",
            field=models.CharField(editable=False, max_length=19, unique=True),
        ),
    ]
