# Generated by Django 5.2.9 on 2026-08-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("licenses", "0002_license_remaining_duration_license_suspended_at_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="licenses",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="licenses",
                to="products.product",
            ),
        ),
    ]
