# Generated by Django 5.2.9 on 2026-07-12 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                3, "Product name must be at least 3 characters"
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(max_length=250)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Security", "Security"),
                            ("Productivity", "Productivity"),
                            ("Design", "Design"),
                            ("Business", "Business"),
                        ],
                        default="Security",
                        max_length=12,
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("Lifetime", "Lifetime"),
                            ("Annually", "Annually"),
                            ("Monthly", "Monthly"),
                        ],
                        default="Monthly",
                        max_length=9,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Archived", "Archived"),
                        ],
                        default="Active",
                        max_length=8,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
